// Code generated by mockery v2.46.3. DO NOT EDIT.

package evmrpc

import (
	context "context"
	big "math/big"

	mock "github.com/stretchr/testify/mock"

	types "github.com/ethereum/go-ethereum/core/types"
)

// MockIOracle is an autogenerated mock type for the IOracle type
type MockIOracle struct {
	mock.Mock
}

type MockIOracle_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIOracle) EXPECT() *MockIOracle_Expecter {
	return &MockIOracle_Expecter{mock: &_m.Mock}
}

// TxFeeUUSDC provides a mock function with given fields: ctx, tx, gasTokenCoingeckoID
func (_m *MockIOracle) TxFeeUUSDC(ctx context.Context, tx *types.Transaction, gasTokenCoingeckoID string) (*big.Int, error) {
	ret := _m.Called(ctx, tx, gasTokenCoingeckoID)

	if len(ret) == 0 {
		panic("no return value specified for TxFeeUUSDC")
	}

	var r0 *big.Int
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *types.Transaction, string) (*big.Int, error)); ok {
		return rf(ctx, tx, gasTokenCoingeckoID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *types.Transaction, string) *big.Int); ok {
		r0 = rf(ctx, tx, gasTokenCoingeckoID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*big.Int)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *types.Transaction, string) error); ok {
		r1 = rf(ctx, tx, gasTokenCoingeckoID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockIOracle_TxFeeUUSDC_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TxFeeUUSDC'
type MockIOracle_TxFeeUUSDC_Call struct {
	*mock.Call
}

// TxFeeUUSDC is a helper method to define mock.On call
//   - ctx context.Context
//   - tx *types.Transaction
//   - gasTokenCoingeckoID string
func (_e *MockIOracle_Expecter) TxFeeUUSDC(ctx interface{}, tx interface{}, gasTokenCoingeckoID interface{}) *MockIOracle_TxFeeUUSDC_Call {
	return &MockIOracle_TxFeeUUSDC_Call{Call: _e.mock.On("TxFeeUUSDC", ctx, tx, gasTokenCoingeckoID)}
}

func (_c *MockIOracle_TxFeeUUSDC_Call) Run(run func(ctx context.Context, tx *types.Transaction, gasTokenCoingeckoID string)) *MockIOracle_TxFeeUUSDC_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(*types.Transaction), args[2].(string))
	})
	return _c
}

func (_c *MockIOracle_TxFeeUUSDC_Call) Return(_a0 *big.Int, _a1 error) *MockIOracle_TxFeeUUSDC_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockIOracle_TxFeeUUSDC_Call) RunAndReturn(run func(context.Context, *types.Transaction, string) (*big.Int, error)) *MockIOracle_TxFeeUUSDC_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockIOracle creates a new instance of MockIOracle. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIOracle(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIOracle {
	mock := &MockIOracle{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
