// Code generated by mockery v2.46.2. DO NOT EDIT.

package svmrpc

import (
	context "context"

	svmrpc "github.com/skip-mev/go-fast-solver/shared/svmrpc"
	mock "github.com/stretchr/testify/mock"
)

// MockSVMRPCClientManager is an autogenerated mock type for the SVMRPCClientManager type
type MockSVMRPCClientManager struct {
	mock.Mock
}

type MockSVMRPCClientManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSVMRPCClientManager) EXPECT() *MockSVMRPCClientManager_Expecter {
	return &MockSVMRPCClientManager_Expecter{mock: &_m.Mock}
}

// GetClient provides a mock function with given fields: ctx, chainID
func (_m *MockSVMRPCClientManager) GetClient(ctx context.Context, chainID string) (svmrpc.SolanaRPCClient, error) {
	ret := _m.Called(ctx, chainID)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 svmrpc.SolanaRPCClient
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (svmrpc.SolanaRPCClient, error)); ok {
		return rf(ctx, chainID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) svmrpc.SolanaRPCClient); ok {
		r0 = rf(ctx, chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(svmrpc.SolanaRPCClient)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSVMRPCClientManager_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockSVMRPCClientManager_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID string
func (_e *MockSVMRPCClientManager_Expecter) GetClient(ctx interface{}, chainID interface{}) *MockSVMRPCClientManager_GetClient_Call {
	return &MockSVMRPCClientManager_GetClient_Call{Call: _e.mock.On("GetClient", ctx, chainID)}
}

func (_c *MockSVMRPCClientManager_GetClient_Call) Run(run func(ctx context.Context, chainID string)) *MockSVMRPCClientManager_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockSVMRPCClientManager_GetClient_Call) Return(_a0 svmrpc.SolanaRPCClient, _a1 error) *MockSVMRPCClientManager_GetClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSVMRPCClientManager_GetClient_Call) RunAndReturn(run func(context.Context, string) (svmrpc.SolanaRPCClient, error)) *MockSVMRPCClientManager_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSVMRPCClientManager creates a new instance of MockSVMRPCClientManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSVMRPCClientManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSVMRPCClientManager {
	mock := &MockSVMRPCClientManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
