// Code generated by mockery v2.46.3. DO NOT EDIT.

package tmrpc

import (
	context "context"

	client "github.com/cometbft/cometbft/rpc/client"

	mock "github.com/stretchr/testify/mock"
)

// MockTendermintRPCClientManager is an autogenerated mock type for the TendermintRPCClientManager type
type MockTendermintRPCClientManager struct {
	mock.Mock
}

type MockTendermintRPCClientManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockTendermintRPCClientManager) EXPECT() *MockTendermintRPCClientManager_Expecter {
	return &MockTendermintRPCClientManager_Expecter{mock: &_m.Mock}
}

// GetClient provides a mock function with given fields: ctx, chainID
func (_m *MockTendermintRPCClientManager) GetClient(ctx context.Context, chainID string) (client.Client, error) {
	ret := _m.Called(ctx, chainID)

	if len(ret) == 0 {
		panic("no return value specified for GetClient")
	}

	var r0 client.Client
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (client.Client, error)); ok {
		return rf(ctx, chainID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) client.Client); ok {
		r0 = rf(ctx, chainID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(client.Client)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, chainID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockTendermintRPCClientManager_GetClient_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetClient'
type MockTendermintRPCClientManager_GetClient_Call struct {
	*mock.Call
}

// GetClient is a helper method to define mock.On call
//   - ctx context.Context
//   - chainID string
func (_e *MockTendermintRPCClientManager_Expecter) GetClient(ctx interface{}, chainID interface{}) *MockTendermintRPCClientManager_GetClient_Call {
	return &MockTendermintRPCClientManager_GetClient_Call{Call: _e.mock.On("GetClient", ctx, chainID)}
}

func (_c *MockTendermintRPCClientManager_GetClient_Call) Run(run func(ctx context.Context, chainID string)) *MockTendermintRPCClientManager_GetClient_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *MockTendermintRPCClientManager_GetClient_Call) Return(_a0 client.Client, _a1 error) *MockTendermintRPCClientManager_GetClient_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockTendermintRPCClientManager_GetClient_Call) RunAndReturn(run func(context.Context, string) (client.Client, error)) *MockTendermintRPCClientManager_GetClient_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockTendermintRPCClientManager creates a new instance of MockTendermintRPCClientManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockTendermintRPCClientManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockTendermintRPCClientManager {
	mock := &MockTendermintRPCClientManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
